# Knowledge Graph to be loaded by default
#knowledge.model.path=${HOME}/opt/hermes_16_10_test.owl
knowledge.model.path=${HOME}/ws/ai/HERMES/hermes_16_10_test.owl
# MongoDB connection 
spring.data.mongodb.uri=mongodb+srv://${MONGO_CLOUD_USER}:${MONGO_CLOUD_PASS}@cluster0.zjmi0.mongodb.net/hermes_ai
spring.data.mongodb.database=hermes_ai
# Server timeout (in milliseconds) for HTTP requests
server.connection-timeout=120s